### PR TITLE
Translation German (issue #31)

### PR DESCRIPTION
**Pull request by weidengeist**
Hello kodolinija,

I have been working on issue #31 and changed everything to make the translation consistent. I have even revised multiple other lines of the translation, however, not everything has been adjusted, yet I am willing to keep contributing.

Additionally, I have written a short Python script which fetches the English terms from Google docs, compares it to an existing language file (first argument passed to the script), and finally merges the existing foreign language terms into the English template. This way, it also adds those terms from the English original file which have not already been integrated into the foreign language file and appends a »TO DO! NO TRANSLATION YET« comment to them so they can be easily found to add the correct corresponding values in the other language.

Please feel free to contact me in case of issues or questions. Looking forward to the »Stardeus« release tomorrow and wish you great success.

Regards,
Weidengeist

### CODE REVIEW

**Comment by spajus** [comment]
Thank you for a pull request! However, before I can accept a contribution, I need a signed CLA, see this section of the main Readme: https://github.com/kodolinija/stardeus-translations#contributor-license-agreement

**Comment by weidengeist** [comment]
Thank you for pointing this out and please excuse for not having submitted the CLA beforehand. I have just sent you the signed CLA.

Regards,
Weidengeist

**Comment by spajus** [comment]
@weidengeist I did not find the email with it, could you confirm you sent to tomas@kodolinija.com ?

**Comment by weidengeist** [comment]
Sent the email again before I read your update. You may ignore the second one, of course.

**Comment by spajus** [comment]
@weidengeist I'm looking at the PR but there are a few isues.

The python script:
1. It completely overwrites the existing file, which messes up the diff for others who are working on the translation (@TheInnos). 2. It adds "TODO" in comments, the comment column is supposed to provide context for the translator, and I would think that it's best to keep the comment exactly as in the original. Version field also must match to the original, or the translation key would be marked as incompatible.
3. The recommended way is to use Google Sheets to translate and then export the result as CSV, as editing CSV directly can be a nightmare with all the escape characters and formatting, and having this python script goes against the recommendation. I do not want to include it to the main translations repository.

I also see another issue, with English translation copied over in certain keys, like `no.terraformable.help`, since the script rewrites everything, it is also difficult to tell if it was like that before the change.

The problem with using English in translations is that then the in-game tooling that validates the translation cannot tell if the key is translated or not, it will show up as translated and will mess up the completeness statistic.

So in order to merge this PR, you would have to:
1. Remove the python script - you can put it up to your personal repo or a gist, I know some would find it useful (like @unggod who also doesn't use Google Sheets) - but the script should not copy English versions and should not modify the comment column.
2. Make the changes to `German.csv` less destructive to the version history (unless @TheInnos confirms it's ok)
3. Remove the "TODO" comments that the script has added

**Comment by weidengeist** [comment]
Thank you very much for your extensive feedback.

I see the issues with copying the English keys to the translation file. The Python script will be put to my personal repository, revised according to your suggestions, and removed from the pull request.

During the current day I am steadily working on the translation from top to bottom and will hopefully be done by the end of the day, which will eventually also include the parts not yet translated for German language. The comments will, of course, be restored and the TODOs will be removed. I can also integrate those new translations and changes into the latest accepted commit to make the changes less destructive to the version history, however, I suggest having the same alphabetical order as the English document does, which is not the case at the moment. Comparing translation sheets would be easier then. Sorting the keys would be a great break in the version history indeed, but possibly with a good reason. Maybe @TheInnos will agree, but I don’t insist on that as long as there is progress in the »Stardeus« localization project.

**Comment by spajus** [comment]
@weidengeist you could also submit the changes to the translations in smaller chunks in separate PRs, it's easier to review them this way, and less chance of clashing with someone else

**Comment by weidengeist** [comment]
Hi Spajus,

I have reverted the German language file to the latest accepted commit and revised the whole `codex` key section. This should also include the majority – if not all – of the occurrences of mixed up »Sie« and »Du« mentioned in issue #31. So the changes in the version history are now reduced to a minimum. All deletions in the report are the result of resorting the `codex` key section and gathering `codex` key entries which were scattered across the file.

The Python script has been removed from the pull request.

Regards,
Weidengeist

**Comment by spajus** [comment]
Thank you!

**Pull request merged**
