### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by Ketyak**
It's my first time, please be gentle.

If I did anything wrong, please tell me what and how to avoid it.

### CODE REVIEW

**Comment by spajus** [comment]
Thank you for the contribution! A couple of questions before I merge:
1. I did receive a signed CLA from `k********i@o******.com` email address - please confirm it was from you
2. Did you use the "Generate Validity Report" tool to validate the translation in-game?

**Comment by Ketyak** [comment]
Hi


  1.  Yes, that's me
  2.  I'm sorry, I don't know what that is. All my commits to myself had this green 'Verified' next to them if that's what you mean

________________________________
Od: Tomas Varaneckas ***@***.***>
Wysłane: niedziela, 23 października 2022 07:40
Do: kodolinija/stardeus-translations ***@***.***>
DW: Ketyak ***@***.***>; Author ***@***.***>
Temat: Re: [kodolinija/stardeus-translations] Polish translation (PR #130)


Thank you for the contribution! A couple of questions before I merge:

  1.  I did receive a signed CLA from ***@***.*********.com email address - please confirm it was from you
  2.  Did you use the "Generate Validity Report" tool to validate the translation in-game?

**Comment by Ketyak** [comment]
Oh, apologies, I see now it's an in-game thing.
I'll do it right away
________________________________
Od: Kajetan Malczewski ***@***.***>
Wysłane: niedziela, 23 października 2022 11:23
Do: kodolinija/stardeus-translations ***@***.***>
Temat: ODP: [kodolinija/stardeus-translations] Polish translation (PR #130)

Hi


  1.  Yes, that's me
  2.  I'm sorry, I don't know what that is. All my commits to myself had this green 'Verified' next to them if that's what you mean

________________________________
Od: Tomas Varaneckas ***@***.***>
Wysłane: niedziela, 23 października 2022 07:40
Do: kodolinija/stardeus-translations ***@***.***>
DW: Ketyak ***@***.***>; Author ***@***.***>
Temat: Re: [kodolinija/stardeus-translations] Polish translation (PR #130)


Thank you for the contribution! A couple of questions before I merge:

  1.  I did receive a signed CLA from ***@***.*********.com email address - please confirm it was from you
  2.  Did you use the "Generate Validity Report" tool to validate the translation in-game?

**Comment by Ketyak** [comment]
Hi

I checked the validation report, do I need to attach it somewhere or is the file made just to help me?
________________________________
Od: Tomas Varaneckas ***@***.***>
Wysłane: niedziela, 23 października 2022 07:40
Do: kodolinija/stardeus-translations ***@***.***>
DW: Ketyak ***@***.***>; Author ***@***.***>
Temat: Re: [kodolinija/stardeus-translations] Polish translation (PR #130)


Thank you for the contribution! A couple of questions before I merge:

  1.  I did receive a signed CLA from ***@***.*********.com email address - please confirm it was from you
  2.  Did you use the "Generate Validity Report" tool to validate the translation in-game?

**Comment by spajus** [comment]
Thanks for confirming! The validation report is just for you :)

**Comment by spajus** [comment]
@Ketyak could you update Readme.md and put your credits in there, I will use same line for the in-game credits as well

**Comment by Ketyak** [comment]
Yes, I'll do it later today
________________________________

**Pull request merged**
