### PR TITLE
Fix + New

### PR DESCRIPTION
**Pull request by AndyDL24**
New string and tutorial and fix for IT

### CODE REVIEW

**Comment by spajus** [comment]
Hi @AndyDL24, your pull request currently has no changes. I think you may want to reintroduce this commit: https://github.com/kodolinija/stardeus-translations/pull/320/commits/9ad8dc5a6f02bcda40da160fa85d7c02c613fc93

**Comment by AndyDL24** [comment]
Yes, sorry, but github desktop crashed and I didn't quite understand what it did

**Comment by spajus** [comment]
@AndyDL24 according to the info in this pull request the changes you added were also reverted back, so the pull request is effectively empty.

Here is the raw file with your changes: https://raw.githubusercontent.com/kodolinija/stardeus-translations/9ad8dc5a6f02bcda40da160fa85d7c02c613fc93/Translations/Italian.csv

You may need to close this pull request, synchronize the repository and make a new pull request.

**Comment by spajus** [comment]
@AndyDL24 if you need help recreating your pull request, let me know, I can do it for you.

**Comment by AndyDL24** [comment]
If I can I'll send you the file on discord.  Now I'm at work and I can't use the PC

**Comment by spajus** [comment]
@AndyDL24 I already extracted your updates from this pull request in [this commit](https://github.com/kodolinija/stardeus-translations/commit/492e9f97bcf8f1d16e3f6a2ac8df11588d7d7d4b), you can synchornize your fork in github desktop and it should all be there.

**Comment by AndyDL24** [comment]
Ok perfect, thank you very much.

**Pull request closed without merging**
