### PR TITLE
Feature/translate french

### PR DESCRIPTION
**Pull request by LQ-Sebastien**

### CODE REVIEW

**Comment by LQ-Sebastien** [comment]
Hello Kodolinija :)

I modified a lot of translations that were not very consistent with the events in Stardeus

I found others that I have not yet corrected, I continue as I find them.

Sincerely,
Sebastien

**Comment by spajus** [comment]
Hey @LQ-Sebastien, thank you for the contribution! Would you mind sending me a signed Contributor License Agreement, I can only accept external contributions after the CLA is signed. Here's more info: https://github.com/kodolinija/stardeus-translations#contributor-license-agreement

**Comment by LQ-Sebastien** [comment]
Hey Kodolinija,
I sent you the signed CLA last night around 10:00pm on your mailbox ^^

**Comment by spajus** [comment]
Found it! It went to spam folder.

**Comment by spajus** [comment]
@rem02 could you give this PR a quick look?

**Comment by LQ-Sebastien** [comment]
There is just a small clonflit on some dialogue lines, you can see "" at the ends of sentences that was modified by @rem02 5-10 minutes before my PR. Do I need to change this for the PR?

**Comment by rem02** [comment]
@spajus I read the corrections and it's good for me!
Thanks @LQ-Sebastien for this review ^^

**Pull request merged**
