### PR TITLE
Update German.csv

### PR DESCRIPTION
**Pull request by AndreasBecker84**
Structure adapted to the English template and errors removed. However, various translations are still missing.

### CODE REVIEW

**Comment by spajus** [comment]
Hey @AndreasBecker84, thank you for the contribution!

You will have to sign and send me a Contribution License Agreement in order for me to be able to accept an external commit. Please read the main README.md section about the CLA for more details.

Also, since there are other people contributing to German translation already, I am not sure if it's OK to overwrite the whole file without consulting with everyone. 

@weidengeist @TheInnos @K-Win - please let me know what you think.

**Comment by weidengeist** [comment]
Hey @spajus, @TheInnos, @K-Win, and @AndreasBecker84,

overwriting the whole file is indeed a huge step., which I’d rather discourage from taking. I would vote for a compromise, though: using the most recent accepted commit of the translation file, sorting the keys so their order equals the one of the English template file, and contributing keys to the German file in the exact same order as in the English file from that point on.

**Comment by spajus** [comment]
@nickers has pointed out that a full rewrite of the file will be necessary, because there is a new column, so this could actually be unavoidable. Still, since comments are missing, this will need to be added / synchronized.

**Comment by weidengeist** [comment]
Is there a mandatory amount and order of columns in the translation files? The current translation files mostly contain only key, value, and comment columns each. Should the version column from the English template also be preserved? I guess that depends on the logic of how the game reads the translation files.

**Comment by spajus** [comment]
@weidengeist did you use any of this translations in #118 PR? I would like to resolve this issue, likely this will have to be closed, but if you used anything from this PR I would like to add the author to credits.

**Comment by weidengeist** [comment]
@spajus No, I didn’t. I have been working solely on my own translation file for PR #118.

**Comment by spajus** [comment]
@AndreasBecker84 sorry for the misunderstanding, I appreciate your effort in helping out. It's my bad, I should have prompted new contributions to discuss the intent first, so all collaborators of a language would be aware of who would be doing what. I will update the documentation.

**Pull request closed without merging**
