### PR TITLE
Update French.csv

### PR DESCRIPTION
**Pull request by VizardAlpha**
Addition of missing translations and small sorting from A to Z.
Finally fixed the conflict issue it seems. My main branch was not up to date correctly and when I edited the French.csv file I had not retrieved the translations already done by another person.

### CODE REVIEW

**Comment by spajus** [comment]
@VizardAlpha I would suggest to refrain from shuffling the order of the file unless the original order changes. This can break the workflow of other people who are working on this file (i.e. @rem02). It's best to make minimal changes when possible. 
If @rem02 is OK with this change we can merge though.

**Comment by VizardAlpha** [comment]
Exactly nothing should happen even if someone corrects syntax errors for example, it will just move the text to another level without creating a "conflict", if there is a conflict if the user is using GitHub deskop, it will offer to correct it with a copy and paste, but it should not have anything. As I have added the new translation and moved some text. 
We will wait if rem is currently also working on the translation.

**Comment by rem02** [comment]
Thank you for your work.
For me, there is no problem ^^
I had to check the order because I had seen errors... 
Thank you

**Comment by spajus** [comment]
Thank you!

**Pull request merged**
