### PR TITLE
Feature/ptbr updates

### PR DESCRIPTION
**Pull request by xupisco**
- Updated to latest game version
- Fixes typos
- Better spelling

Will continue the fixes while playing the game (still with demo though)

### CODE REVIEW

**Comment by spajus** [comment]
@xupisco Thank you for your contribution! However, please note that you have to send in a copy of signed Collaborator License Agreement before your contribution can be accepted. Please look at README.md in this repository for more information.

@unggod can you take a look at these changes?

**Comment by unggod** [comment]
i will take a look , but as i can see , it is going the translation to a T route, while mine is adapted after playing for long hours.
some typos, specially Upper case case , will help on my end as reminder to fix it, some dont make sense ex:
achievement.OnePiece,Zerado,, 
zerado can be seems as "cleared" , but cleared of what? the achievment is just to make everything in one piece.
since it is 2k changes, will take some time to review it all.

**Comment by xupisco** [comment]
@unggod "Zerado" also means "Novo"... specially in a case where something is already used but looks like new "...the achievement is just to make everything in one piece".

I did not touch in your "slangs" (HUECoins that doesn't make sense, among others "funny" stuff), just tried to improve, as you said, capitals, punctuation, accents (tons of erros), etc...

Feel free to accept, use or ignore it.  
Hugs.

**Comment by unggod** [comment]
ter uma visão diferente ajuda a ver coisas que passaram por eu estar viciado na minha própria escrita, alguns termos foram encurtados pois tinha redundância e explicações demais, enquanto outros foram adaptados para como nossa lingua funciona , o adj Active por exemplo no ingles usado, fica a cargo de estar disponível , enquanto para nos algo ativo é algo em ação, então mudei para apto pois cobre os dois casos , fora adaptações , como mudei a câmara de clonagem para câmara de cultura pq ela também pode crescer proteína , então chamar de clonagem poderia ser confuso , além de eu também modificar para fica mais claro o que uma coisa faz , o robô de limpeza só limpa o chão, então chama-lo de só limpa chão, explica melhor que não será ele a limpar banheiros e duchas sujas . mais agradeço a ajuda a detectar esses erros .

**Comment by spajus** [comment]
@xupisco I would love to accept it but an email with a photo of a signed Contributor License Agreement is required for any contributions, I cannot accept anything without it for legal reasons.

**Comment by xupisco** [comment]
@spajus Hi, sorry for the delay... just sent the CLA by email.

**Comment by spajus** [comment]
@xupisco thank you! You can make a PR to add yourself to the README contributors list, I'll then use that entry in credits in-game

**Pull request merged**
